services:
  combined:
    restart: unless-stopped
    image: fin
    build:
      context: .
      dockerfile: Dockerfile
    command: ./app combined
    environment:
    - CONFIG_FILE_NAME=develop
    - CONFIG_FILE_TYPE=env
    ports:
    - 11011:8080
    - 11012:9000
    networks:
    - fin_network
networks:
  fin_network:
    driver: bridge
    external: true